# Generated by Django 5.1 on 2024-08-14 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_language', models.CharField(default='EN', max_length=10)),
                ('calendar_view', models.BooleanField(default=True)),
                ('intelligent_scheduling', models.BooleanField(default=False)),
                ('notification_preferences', models.BooleanField(default=True)),
                ('privacy_security_settings', models.BooleanField(default=True)),
                ('analytics_reporting', models.BooleanField(default=True)),
                ('multi_lingual_support', models.BooleanField(default=True)),
                ('security_compliance', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
